apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: base-pvc
  namespace: longhorn-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 256Mi
