kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-storage
  namespace: longhorn-system

provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "90"
  fsType: "ext4"
  # diskSelector: "ssd"
  # nodeSelector: "ssd"
