apiVersion: v1
kind: Service
metadata:
  namespace: games
  name: minecraft-svc
spec:
  selector:
    name: minecraft-dpl
  ports:
    - name: udp
      port: 25565
      protocol: UDP
      targetPort: 25565
    - name: tcp
      port: 25565
      protocol: TCP
      targetPort: 25565
    - name: rtcp
      port: 7864
      protocol: TCP
      targetPort: 25565
    - name: rudp
      port: 7865
      protocol: UDP
      targetPort: 25565
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.3.210
