kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: games
  name: minecraft-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage
  resources:
    requests:
      storage: 2Gi
