kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: games
  name: minecraft-dpl

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      name: minecraft-dpl
  template:
    metadata:
      labels:
        name: minecraft-dpl
    spec:
      containers:
        - name: minecraft-container
          image: marctv/minecraft-papermc-server:latest
          tty: true
          stdin: true
          resources:
            requests:
              memory: 1.5Gi
              cpu: "1"
            limits:
              memory: "2Gi"
              cpu: "2"
          env:
            - name: TZ
              value: "America/Sao_Paulo"
            - name: MEMORYSIZE
              value: "1G"
            - name: EULA
              value: "TRUE"
            - name: PUID
              value: "9999"
            - name: PGID
              value: "9999"
            - name: SERVER_PROXY_IP
              value: "168.138.147.157"
            - name: SERVER_PROXY_PORT
              value: "25565"
          ports:
            - containerPort: 25565
              name: tcp
              protocol: TCP
              hostPort: 25565
          volumeMounts:
            - name: minecraft-pv-mount
              mountPath: /data
      volumes:
        - name: minecraft-pv-mount
          persistentVolumeClaim:
            claimName: minecraft-pvc

      terminationGracePeriodSeconds: 5

      restartPolicy: Always
