---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kuma-uptime
  namespace: longhorn-system
  labels:
    app: kuma-uptime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuma-uptime
  template:
    metadata:
      labels:
        app: kuma-uptime
    spec:
      containers:
        - name: kuma-uptime
          image: louislam/uptime-kuma:1
          resources:
            requests:
              memory: "64Mi"
              cpu: "512m"
            limits:
              memory: "256Mi"
              cpu: "1"
          ports:
            - containerPort: 3001
              protocol: TCP
              name: http
              hostPort: 3001
          volumeMounts:
            - name: kuma-uptime
              mountPath: /app/data
      volumes:
        - name: kuma-uptime
          persistentVolumeClaim:
            claimName: base-pvc
