apiVersion: v1
kind: Service
metadata:
  namespace: tools
  name: kuma-svc
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.3.215
spec:
  selector:
    name: kuma-dpl
  ports:
    - name: http
      port: 80
      targetPort: 3001
  type: LoadBalancer
