kind: PersistentVolume
apiVersion: v1
metadata:
  namespace: tools
  name: kuma-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/srv/dev-disk-by-uuid-eeabf72e-2e04-4c04-ac7d-26e8b134abdf/KUBERNETES/internal-tools-kuma"

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: tools
  name: kuma-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 256Mi
